version: '3'
services:
  api:
    container_name: api_container
    image: node:20
    ports:
      - "4444:4444"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/app/db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  mongo_data:
networks:
  mynetwork:
    driver: bridge